### ISSUE TITLE
"Failed to extract archive" prints a lot of garbage

### ISSUE THREAD

**Issue by tversteeg** [arzg/vim-strand#10]
When I try to install a plugin that has an error (for example with `sheerun/vim-polyglot`) I get `Error: failed to extact archive while installing plugin form URL https://codeload.github.com/sheerun/vim-polyglot/tar.gz/master -- got from server: ` followed by a lot of garbage. Can this print be removed so my console isn't filled with the bytes of a binary application?

**Comment by lunacookies** [comment]
> Can this print be removed

Sure, I’ll add it now.

**Comment by lunacookies** [comment]
Sorry, I can’t seem to reproduce this. Are you on the latest version? Because the error message you are talking about was introduced in [this commit](https://github.com/arzg/vim-strand/commit/db06e79b3e8a1015c9c2258a8a8c1a4291e181f1). Since [this commit](https://github.com/arzg/vim-strand/commit/ca456b0cb3886304e91b6bd43fec2f3271ee484d), however, plugin error messages have been displayed in each plugin’s spinner text area.

**Comment by tversteeg** [comment]
Oh sorry that seems to be the problem yeah, I thought I updated it but apparently I had it installed twice.
