### ISSUE TITLE
Adding plugins using the command line

### ISSUE THREAD

**Issue by tversteeg** [arzg/vim-strand#3]
Feature request:

Being able to add a plugin using the command line, e.g. `strand install tpope/vim-surround`

**Comment by lunacookies** [comment]
Would you prefer for this to append to the config file automatically? And how would you prefer for it to handle different plugin formats? (currently there’s only `GitHub` and `Archive`, but I am likely to add `GitLab` and possibly others)

**Comment by tversteeg** [comment]
I think appending it automatically is a good idea.

For different formats, maybe use a hierarchy of a full URL, a flag and a default?
Something like:

- `strand install gitlab.com/tpope/vim-surround` (GitLab)
- `strand install --bitbucket tpope/vim-surround` (BitBucket)
- `strand install tpope/vim-surround` (GitHub)

**Comment by lunacookies** [comment]
Do you think it’s a good idea to replace the current

```
- GitHub:
    user: abc
    repo: xyz
    git_ref: develop
```

notation with something like

```
- GitHub:
    path: abc/xyz
    git_ref: develop
```

for consistency? I’m not entirely happy with how wordy this (and the current config for that matter) is – I’d much prefer one line per plugin. Then again, this might be difficult with fields other than the `path`. Maybe provide an alternate short form?

```
- GitHub: abc/xyz:develop
```

**Comment by tversteeg** [comment]
I prefer the short form. Or would it be possible to support both at the same time? That way there's still room for more options but it's also more concise when preferred.

**Comment by lunacookies** [comment]
I’m not entirely sure how to go about implementing the short form (while keeping the long form) without creating my own parser, which I would like to avoid at all costs. Any ideas?

**Comment by tversteeg** [comment]
In that case the long form seems fine to me, or alternatively a format like TOML would fit perfectly in this case I think (if you consider that).

**Comment by lunacookies** [comment]
Why do you think TOML would fit better than YAML in this case?

**Comment by lunacookies** [comment]
> Any ideas?

I guess I could create a separate enum variant called `GitHubLongForm`, but that doesn’t seem very nice to me.

**Comment by tversteeg** [comment]
With TOML you could do something like this:

```toml
[GitHub]
"abc/xyz" = {branch = "develop"}
```

Which also allows you to do:

```toml
[GitHub]
"abc/xyz".branch =  "develop"
```

**Comment by lunacookies** [comment]
What kind of struct would this parse into in Rust?

**Comment by tversteeg** [comment]
Something like this I think (copied from the TOML parser in Cargo and not tested)

```rust
#[derive(Deserialize, Serialize, Clone, Debug, Default)]
#[serde(rename_all = "kebab-case")]
pub struct DetailedTomlGithub {
    branch: Option<String>,
}

#[derive(Clone, Debug, Serialize)]
#[serde(untagged)]
pub enum TomlGithub {
    Simple(String),
    Detailed(DetailedTomlGithub),
}

#[derive(Debug, Deserialize, Serialize)]
#[serde(rename_all = "kebab-case")]
struct TomlConfig {
    github: Option<BTreeMap<String, TomlGithub>>,
}
```

**Comment by lunacookies** [comment]
Maybe something along these lines?

```rust
#[derive(Deserialize)
struct ShortGitHubPlugin(String, String, String)

#[derive(Deserialize)]
struct LongGitHubPlugin {
    user: String,
    repo: String,
    git_ref: Option<String>,
}

#[derive(Deserialize)]
#[serde(untagged)]
enum GitHubPlugin {
    ShortForm(ShortGitHubPlugin),
    LongForm(LongGitHubPlugin),
}
```

**Comment by lunacookies** [comment]
Do you think that the proposed `install` subcommand should append to the config file and then reinstall _all_ plugins, or just install that one plugin?

**Comment by lunacookies** [comment]
Can you try out 7fdb93f? At the moment it completely regenerates the config, which leads to it being littered with `git_ref`s, as well as stripping all whitespace and comments. Note that I just changed the config format, so you might have to update yours.

**Comment by tversteeg** [comment]
Shouldn't it detect automatically which plugins need to be installed? Similar to when you add a new line to Vim plug and do `:PlugInstall`.

`install-git --provider .. --user .. --repo ..` seems to work fine but it would probably be nicer if I can just pass a full URL and those fields are inferred from that. Also is the distinction between `install-git` and `install-tar` necessary?

**Comment by lunacookies** [comment]
> Shouldn't it detect automatically which plugins need to be installed?

Up to this point, running `strand` has always deleted all plugins and reinstalled them fresh. This avoids the need for `PlugClean` and `PlugUpdate`. However, I can see that for this `install` command it may be better to just install the one.

> it would probably be nicer if I can just pass a full URL

I’m currently working on the shorthand we discussed earlier. Here’s the config example from the README with the new syntax:

```yaml
---
plugin_dir: ~/.vim/pack/strand/start
plugins:
  # GitHub and Bitbucket repos are both fully supported
  - Git: github@tpope/vim-surround
  - Git: bitbucket@vim-plugins-mirror/vim-surround
  - Git: github@neoclide/coc.nvim:release # Specify a branch name,
  - Git: github@tpope/vim-unimpaired:v2.0 # a tag name,
  - Git: github@romainl/vim-qf:4a97465    # or a commit hash.

  # Or just plain tar.gz archive URLs
  - Archive: https://codeload.github.com/romainl/vim-qlist/tar.gz/master
```

This actually works at the moment – I’m just busy cleaning up the ‘parser’ for the shorthand. Once this is completed I could reuse the same code to parse command-line arguments too.

> is the distinction between install-git and install-tar necessary

This is the way it is because I decided it would be easier to add `#[derive(StructOpt)]` to the `struct`s/`enum`s that were already in place for plugins, instead of essentially copy-pasting some code with a few minor modifications. Again, when the shorthand is complete both `ArchivePlugin` and `GitRepo` will be representable by a single `String`, so this distinction can be removed. Although I haven’t actually looked into it, it would be ideal if there was a way to get StructOpt to parse an input argument (in this specific case the shorthand form) into a desired type using a desired function.

**Comment by lunacookies** [comment]
The new shorthand has now been instated, so it should be quite easy to finish up the subcommand. It’s quite late over here, so I think I’ll work on it tomorrow.

Could you please also take a look at [this](https://github.com/arzg/vim-strand/blob/ebfc64ea67b57640c870b64b8df80e5e4d7334ee/src/lib.rs#L138)? I spent a very long time trying to get an approach involving the mutation of a slice (`s = &s[x..]` in `split_on_pattern()`) each iteration to work, but had some problems with mutable borrows. I eventually went the easy (and admittedly messy) way out with a numerical index. I’ve never written a parser before, so I would definitely like to know if there is a better way to do this.

Thanks.

**Comment by tversteeg** [comment]
Awesome, that all looks great to me!

**Comment by tversteeg** [comment]
This can be easily done using the [`url`](https://docs.rs/url/2.1.0/url/) crate that `surf` already exports, here's a small snippet that does some of the parsing, you can extend it however you want:

```rust
        let url = surf::url::Url::parse(&input).unwrap();

        // Default to GitHub when the provider is elided.
        let provider = match url.host_str() {
            Some("github.com") => GitProvider::GitHub,
            Some("bitbucket.com") => GitProvider::Bitbucket,
            Some(_) => GitProvider::GitHub,
            None => GitProvider::GitHub
        };

        // Get the first two segments after the first "/".
        let mut repo_and_user: Vec<String> = url
            .path_segments()
            .map(|c| c.collect::<Vec<_>>())
            .expect("Something went wrong parsing URL")
            .iter()
            .take(2)
            // Convert the &str reference to String types
            .map(|c| c.to_string())
```

**Comment by lunacookies** [comment]
I’ve been thinking about the best way of representing the current format in a URL, and have come to the conclusion that this approach might not fit the shorthand very well:

Here is the current shorthand – parts in bold are not guaranteed to be in every input: 

> **provider @** user / repo **: git_ref**

I think it is a good first step to try representing providers with the host of the URL, and separate `git_ref` with another slash:

> https:// **provider.com /** user / repo **/ git_ref**

However, `url`’s `parse()` [only accepts absolute URLs](https://docs.rs/url/2.1.0/url/struct.Url.html#method.parse) – AFAIK this means that the **provider.com /** prefix is needed. Once we start to circumvent this (i.e. introduce some custom parsing logic) I feel the tradeoff of having to use a less ergonomic format for less implementation work starts to make less sense.

If I’m missing something here I’d love to know because I’m all for simplifying the (currently messy) parser.

**Comment by lunacookies** [comment]
> is the distinction between `install-git` and `install-tar` necessary?

I’ve been trying to create an `install` subcommand with the new shorthand, but realised that the following setup

```bash
> strand install --git tpope/vim-surround
> strand install --git bitbucket@vim-plugins-mirror/vim-surround
> strand install --tar https://codeload.github.com/romainl/vim-qlist/tar.gz/master
```

leads to the problem of being able to specify both `--git` and `--tar`. I’m not sure if it’s possible to define two mutually exclusive flags with StructOpt, so the only way to keep the two separate is by creating two subcommands. On the other hand, you could say that specifying multiple plugins is actually desirable! This is what I have in mind to accomplish what the three commands from above accomplish in just one command:

```bash
> strand install --git tpope/vim-surround --git bitbucket@vim-plugins-mirror/vim-surround --tar https://codeload.github.com/romainl/vim-qlist/tar.gz/master
```

What do you think of this? I think specifying multiple plugins could actually be useful in some scenarios, and would simplify implementation somewhat.

**Comment by arzg** [comment]
I’ve added support in ce10a1c for using the install subcommand with multiple instances of the same shorthand as the config uses:

```bash
> strand install tpope/vim-surround bitbucket@vim-plugins-mirror/vim-surround github@neoclide/coc.nvim:release https://codeload.github.com/romainl/vim-qlist/tar.gz/master # etc
```

**Comment by lunacookies** [comment]
I’ve added support in ce10a1c for using the install subcommand with multiple instances of the same shorthand as the config uses:

```bash
> strand install tpope/vim-surround bitbucket@vim-plugins-mirror/vim-surround github@neoclide/coc.nvim:release https://codeload.github.com/romainl/vim-qlist/tar.gz/master # etc
```

Any suggestions before I merge?

**Comment by tversteeg** [comment]
I think for now it's a good solution, you put a lot of effort into it. Too bad the `url` crate didn't work out as intended. If you still want to look further into it here's how Cargo parses the Git URL's: https://github.com/rust-lang/cargo/blob/35c55a93200c84a4de4627f1770f76a8ad268a39/src/cargo/core/source/source_id.rs#L110

**Comment by lunacookies** [comment]
> If you still want to look further into it here's how Cargo parses the Git URL's

That’s definitely an interesting approach – using a uniform separator for fields instead of varying ones really seems to simplify the implementation. Maybe something like `github/user/repo/ref` instead of `github@user/repo:ref` in strand’s case … Anyway, that would mean it would be difficult to tell whether the user has an invalid Git provider or has simply omitted that field.

> I think for now it's a good solution, you put a lot of effort into it.

Thank you (don’t forget that you helped a lot too!), I’ll merge now.

**Comment by tversteeg** [comment]
By the way I just checked the [accepted URL parameters for `git clone`](https://www.git-scm.com/docs/git-clone#_git_urls_a_id_urls_a), and their way to handle URLs seems quite easy, maybe it's an idea to keep to those conventions?

**Comment by lunacookies** [comment]
Good find! So are you suggesting that `provider@abc/xyz:ref` is changed to `provider:abc/xyz` (going off the simplest-looking syntax, scp-like) … and then what about the `ref`?

**Comment by tversteeg** [comment]
Maybe add it as a separate flag, and get the default value when the flag's not set? Seems a good idea to keep the conventions of widely used tools like git.

**Comment by lunacookies** [comment]
> as a separate flag

This would mean that every Git plugin in the config would take more than one line, which is unideal. Additionally, the command-line parsing of the shorthand is currently handled transparently by StructOpt, making use of the `FromStr` trait. If a `GitRepo` is not representable by a `&str` this would have to become more complex.

**Comment by tversteeg** [comment]
> > as a separate flag
> 
> This would mean that every Git plugin in the config would take more than one line, which is unideal. Additionally, the command-line parsing of the shorthand is currently handled transparently by StructOpt, making use of the `FromStr` trait. If a `GitRepo` is not representable by a `&str` this would have to become more complex.

That's true but isn't it uncommon to actually specify the ref yourself? So maybe it shouldn't be a flag but if you use the shortened URL you can only specify that, and when you want to add the ref you have to do it manually using the long version.

**Comment by lunacookies** [comment]
> isn't it uncommon to actually specify the ref yourself

I would say that’s true.

> you have to do it manually using the long version

I get that it would be ideal for the shorthand to be in some kind of canonical or familiar format, but I think if the shorthand is available then people will only use that instead of the long version. Personally I think that less choice in this area is better, so that it’s easier to skim others’ configs without having to remember the two formats.

For new users it might be kind of confusing to have to say that here we have this familiar syntax, you use it like this, you can use it in the config and in the `install` subcommand, etc., etc, only then having to explain you have to use this completely different, longer syntax if you want to pin a plugin to a commit, branch or tag.

My opinion is that it would be better to add just one bit of non-standard syntax for Git references, instead of adding a whole different syntax for users to learn.

**Comment by tversteeg** [comment]
Those are valid points, I'm quite happy with your current solution.

**Comment by lunacookies** [comment]
👍

**Comment by lunacookies** [comment]
I’ve been trying to get GitHub Actions to work throughout today – I am extremely close to getting it finished. Throughout the day I’ve been force-pushing a lot to avoid littering the history with tens of commits of me changing something and hoping it works :/

**Comment by tversteeg** [comment]
I had the same problem a lot, it's very annoying that you have to do a commit for that, especially when testing releases. Maybe creating a new branch would make it easier? In that case you can just discard the branch and copy the changes.

Also, are you planning on publishing your crate on cargo? That would be very nice for getting updates of this tool. I can recommend this tool for making it easy with tags and stuff: https://github.com/sunng87/cargo-release

**Comment by lunacookies** [comment]
> Maybe creating a new branch would make it easier?

I’ll definitely keep that in mind in future, but I’m so close at the moment that I don’t think it’s worth it.

> Also, are you planning on publishing your crate on cargo?

I’d definitely consider it if people would find it useful. I’ve never published anything on Cargo, so I’ll take a look :)

**Comment by tversteeg** [comment]
Publishing on Cargo is surprisingly easy, especially with the link I shared. I can help you if you would like that.

**Comment by lunacookies** [comment]
> I can help you if you would like that.

That would be great, but I’d like to finish the CI/CD setup first.

On a completely unrelated note, what do you think of the new fancy UI?

**Comment by lunacookies** [comment]
Hooray! CI/CD is now fully-functional!

**Comment by tversteeg** [comment]
Awesome!
